In [ ]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [4]:
import tensorflow as tf

In [5]:
print(tf.__version__)

2.15.0


In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
sent = [
    'I am a good boy',
    'I like to drink tea',
    'we will we will rockyou',
    'Is this the real life',
    'Is this just fantasy'
]

In [8]:
sent

['I am a good boy',
 'I like to drink tea',
 'we will we will rockyou',
 'Is this the real life',
 'Is this just fantasy']

In [9]:
vocab_size = 500

In [10]:
oneh_repr = [one_hot(word , vocab_size) for word in sent]

In [11]:
print(oneh_repr)

[[305, 318, 200, 370, 252], [305, 251, 217, 419, 365], [261, 80, 261, 80, 412], [280, 200, 178, 455, 282], [280, 200, 130, 284]]


In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
cons_repr = pad_sequences(oneh_repr, padding = 'pre' , maxlen = 8 )
print(cons_repr)

[[  0   0   0 305 318 200 370 252]
 [  0   0   0 305 251 217 419 365]
 [  0   0   0 261  80 261  80 412]
 [  0   0   0 280 200 178 455 282]
 [  0   0   0   0 280 200 130 284]]


In [47]:
# model = Sequential()
# model.add(Embedding(vocab_size , 10 , input_length = 8))
# model.compile('adam' , 'mse')

In [48]:
# model.summary()

In [19]:
cons_repr[0]

array([  0,   0,   0, 305, 318, 200, 370, 252], dtype=int32)

In [34]:
# model.predict(cons_repr)

In [29]:
sentence = "One of the other reviewers has mentioned that after watching just 1 Oz episode you will be hooked. They are right, as this is exactly what happened with me. The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word. It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary."


In [26]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [27]:
from nltk.tokenize import sent_tokenize

In [32]:
another_one = sent_tokenize(sentence)

In [40]:
another_one[2]

'The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO.'

In [35]:
onehot = [one_hot(word , vocab_size) for word in another_one]

In [45]:
padded = pad_sequences(onehot , padding = 'pre' , maxlen = 25)

In [46]:
padded

array([[  0,   0,   0,   0,   0,   0,   0, 200,  58, 178,  18, 137, 324,
        439,  80, 452, 305, 130, 192, 498, 142, 217,  80, 339, 428],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 433, 247, 178, 340, 200, 280, 320, 234, 345, 134, 131],
       [  0, 178, 475, 122,  80, 435, 131,  88, 498, 109, 358, 240, 447,
        117, 296,  58, 109, 206, 351, 419, 178, 480, 178, 287, 462],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 243,
        131, 200, 280, 249, 200, 150, 427, 178,  73, 237, 460, 105],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        200, 150,  31, 202,  88, 134, 399, 217, 221, 338, 460, 109],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0, 358, 280, 423, 419, 178, 162, 343,  58, 178, 287],
       [  0,   0,   0,   0,   0,   0,   0,   0,  76, 280, 138, 498, 340,
         80, 280, 178, 199, 209, 217, 178, 435, 270, 460, 490,   7]],
     

In [55]:
model = Sequential()
model.add(Embedding(vocab_size , 25 , input_length = 25))
model.compile('adam' , 'mse')

In [56]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 25, 25)            12500     
                                                                 
Total params: 12500 (48.83 KB)
Trainable params: 12500 (48.83 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [57]:
model.predict(padded[0])

1/1 [==============================] - 0s 54ms/step


array([[-0.04992566,  0.03388891, -0.00953655,  0.00018588, -0.03197832,
         0.0222186 , -0.02566226, -0.02955401, -0.03886598,  0.01418212,
         0.03308463,  0.01463587,  0.01440475, -0.04974651,  0.03968395,
        -0.02080244, -0.00622611,  0.00382073, -0.03293514,  0.00485414,
        -0.01763129, -0.0038051 , -0.01141833, -0.02746295,  0.01363135],
       [-0.04992566,  0.03388891, -0.00953655,  0.00018588, -0.03197832,
         0.0222186 , -0.02566226, -0.02955401, -0.03886598,  0.01418212,
         0.03308463,  0.01463587,  0.01440475, -0.04974651,  0.03968395,
        -0.02080244, -0.00622611,  0.00382073, -0.03293514,  0.00485414,
        -0.01763129, -0.0038051 , -0.01141833, -0.02746295,  0.01363135],
       [-0.04992566,  0.03388891, -0.00953655,  0.00018588, -0.03197832,
         0.0222186 , -0.02566226, -0.02955401, -0.03886598,  0.01418212,
         0.03308463,  0.01463587,  0.01440475, -0.04974651,  0.03968395,
        -0.02080244, -0.00622611,  0.00382073, -0